version: "3.7"

services:
  
  php:
    build: docker/php
    depends_on:
      - memcached
    volumes:
      - .:/usr/local/src/app

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
